version: "3"

services:
  helx-ui:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
    ports:
      - 80:80
