version: "3"

services:
  appstore:
    image: heliumdatastage/appstore:modify-work-0.7
    entrypoint:
      - /bin/bash
      - -c
      - pip uninstall -y tycho-api && export PYTHONPATH=${PYTHONPATH}:/usr/src/inst-mgmt/tycho && /usr/src/inst-mgmt/bin/appstore start ${DJANGO_SETTINGS}
    volumes:
      - $HOME/.kube/config:/home/appstore/.kube/config
      - $HOME/.minikube/:$HOME/.minikube/
      - ./build/frontend/index.html:/usr/src/inst-mgmt/frontend/templates/frontend/index.html
      - ./build/frontend/:/usr/src/inst-mgmt/frontend/static/frontend
      - ./tycho:/usr/src/inst-mgmt/tycho
    env_file:
      - .env
    ports:
      - 8000:8000