version: "3"

services:
  appstore:
    image: helxplatform/appstore:develop-latest
    volumes:
      - $HOME/.kube/config:/home/appstore/.kube/config
      - $HOME/.minikube/:$HOME/.minikube/
    env_file:
      - .env
    ports:
      - 8001:8000
