version: "3"

services:
  appstore:
    image: helxplatform/appstore:develop-latest
    volumes:
      - $HOME/.kube/config:/home/appstore/.kube/config
      - $HOME/.minikube/:$HOME/.minikube/
      - ./src/build/frontend/static/index.html:/usr/src/inst-mgmt/frontend/templates/frontend
      - ./src/build:/usr/src/inst-mgmt/static
    env_file:
      - .env
    ports:
      - 8000:8000
