# Workflow responsible for the 
# major release processes.
#

name: Build-Push-Release
on:
  # workflow_dispatch:
  #   inputs:
  #     versionTag:
  #       description: 'Tag for new release, ie 1.1.2 .. 4.0.0, etc. 🛑 DO not include the ⍘v⍘ '
  #       required: true
  #       type: string
 #keep ^ commented out after testing
  push:
    # branches:
    #   - master 
    #   - main
    # paths-ignore:
    #   - README.md
    #   - .old_cicd/*
    #   - .github/*
    #   - .github/workflows/*
    #   - LICENSE
    #   - .gitignore
    #   - .dockerignore
    #   - .githooks
    # tags-ignore:
    #   - 'v[0-9]+.[0-9]+.*'
jobs:
  build-push-release:
    uses: helxplatform/helx-github-actions/.github/workflows/build-push-release.yml@develop
    secrets: inherit